completed react-hash-routing exercise
SarahChoung/instructors-curriculum-code-solutions pull request #8
Opened 2021-01-11 04:22 UTC by SarahChoung

![Jan-10-2021 20-19-43](https://user-images.githubusercontent.com/60276373/104147021-93c54e00-5381-11eb-83ff-05e34bc958dc.gif)

2021-01-11 05:03 UTC, thebearingedge requested changes

2021-01-11 05:03 UTC, thebearingedge commented on react-hash-routing/client/app.jsx
> +    }.bind(this));
If you use an arrow function, you won't need to bind this.

2021-01-11 05:03 UTC, thebearingedge commented on react-hash-routing/client/app.jsx
> +      const currentHash = this.state?.route;
??? Nani ???

2021-01-13 03:28 UTC, SarahChoung commented on react-hash-routing/client/app.jsx
> +      const currentHash = this.state?.route;
Gomen'nasai

2021-01-17 20:32 UTC, thebearingedge approved these changes

2021-01-18 00:16 UTC, merged